name: Versioning

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  tag:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: define pattern for versioning
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}},{{minor}}
            type=semver,pattern={{major}}
            type=ref, event=branch